/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPlatoonsRouteImport } from './routes/admin/platoons'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminBatchesRouteImport } from './routes/admin/batches'
import { Route as AdminSoldiersIdRouteImport } from './routes/admin/soldiers/$id'

const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlatoonsRoute = AdminPlatoonsRouteImport.update({
  id: '/admin/platoons',
  path: '/admin/platoons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/admin/batches',
  path: '/admin/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSoldiersIdRoute = AdminSoldiersIdRouteImport.update({
  id: '/admin/soldiers/$id',
  path: '/admin/soldiers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/enroll': typeof EnrollRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/platoons': typeof AdminPlatoonsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/soldiers/$id': typeof AdminSoldiersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/enroll': typeof EnrollRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/platoons': typeof AdminPlatoonsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/soldiers/$id': typeof AdminSoldiersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/enroll': typeof EnrollRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/platoons': typeof AdminPlatoonsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/soldiers/$id': typeof AdminSoldiersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/enroll'
    | '/admin/batches'
    | '/admin/login'
    | '/admin/overview'
    | '/admin/platoons'
    | '/admin/'
    | '/admin/soldiers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/enroll'
    | '/admin/batches'
    | '/admin/login'
    | '/admin/overview'
    | '/admin/platoons'
    | '/admin'
    | '/admin/soldiers/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/enroll'
    | '/admin/batches'
    | '/admin/login'
    | '/admin/overview'
    | '/admin/platoons'
    | '/admin/'
    | '/admin/soldiers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  EnrollRoute: typeof EnrollRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPlatoonsRoute: typeof AdminPlatoonsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSoldiersIdRoute: typeof AdminSoldiersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/platoons': {
      id: '/admin/platoons'
      path: '/admin/platoons'
      fullPath: '/admin/platoons'
      preLoaderRoute: typeof AdminPlatoonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/admin/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/soldiers/$id': {
      id: '/admin/soldiers/$id'
      path: '/admin/soldiers/$id'
      fullPath: '/admin/soldiers/$id'
      preLoaderRoute: typeof AdminSoldiersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  EnrollRoute: EnrollRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPlatoonsRoute: AdminPlatoonsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSoldiersIdRoute: AdminSoldiersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
